#!/usr/bin/python

import sys

def main():
    i = 0
    inp = []
    outp = []
    print sys.argv[1]
    for line in sys.stdin.readlines():
        l = line[:-1]
        if "[" in l:
	    inp = l.split(";")
	if "z" in l:
	    outp = l.split(";")

            sc = ""
	    for j in range(len(inp)):
                sc += inp[j]
                if not len(outp[j].strip()) == 0:
                    sc += "/%s" % outp[j].strip()
                if j < len(inp) - 1:
                    sc += "; "
            print sc
	    inp = []
	    outp = []
	i += 1

if __name__ == '__main__':
    main()
    
